### ISSUE TITLE
ld: error while loading shared libraries: libxar.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by demhademha** [tpoechtrager/cctools-port#100]
When compiling cctools, everything is successful until it gets to this error:
ld: error while loading shared libraries: libxar.so.1: cannot open shared object file: No such file or directory
operating system: Debian 10
Clang v11

**Comment by tpoechtrager** [comment]
Your xar installation is broken. Try to reinstall it.

**Comment by demhademha** [comment]
Fixed by updating and rebooting the system.
