### ISSUE TITLE
Invalid tvOS binaries

### ISSUE THREAD

**Issue by naithar** [tpoechtrager/cctools-port#103]
When uploading project containing library built with `cctools` App Store rejects the app with following error:
```
Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission.
```

Using same library built on macOS results in correct application processing.

I've followed steps from https://github.com/tpoechtrager/cctools-port/issues/31. But using clang from https://opensource.apple.com/tarballs/clang/clang-800.0.42.1.tar.gz resulted in `cctools` not building at all (apple-libtapi and cctools was missing `-lgcc` for some reason).

I've switched to https://github.com/apple/llvm-project and managed to build `cctools`, but binary was still rejected.
Adding https://github.com/tpoechtrager/xar libraries as a dependency for `cctools` (since it seems that they are required for `-fembed-bitcode` and `-bundle_bitcode` to work) also didn't help. 

Also binaries are not exactly corrupted - they do work on both `x86_64` simulator and AppleTV device, but App Store rejects the binary for some reason.

**Edit:**

Also `nm /opt/compiler/apple-clang/lib/libLTO.so |grep lto_codegen_hide_symbols` from #31 didn't return anything.

**Comment by tpoechtrager** [comment]
Compare the bitcode files and check what's different. I don't know of a different solution.

https://llvm.org/docs/CommandGuide/llvm-bcanalyzer.html

**Comment by naithar** [comment]
`llvm-bcanalyzer` returns `llvm-bcanalyzer: Invalid record at top-level` for both (working and corrupt) tvOS libraries.

Any reason `libLTO.so` built from https://github.com/apple/llvm-project doesn't contain `lto_codegen_hide_symbols `? Maybe that's the source of the issue? macOS built binary is 10 MB smaller then one build with cctools.

**Comment by tpoechtrager** [comment]
I don't know. Maybe `lto_codegen_hide_symbols` is not upstreamed on purpose.

**Comment by naithar** [comment]
Using `-flto` seems to be fixing App Store review issue. It requires a lot more time to build the project using such library, but it's better than nothing.

**Comment by tpoechtrager** [comment]
Interesting. `-flto=thin` should speed it up a bit.

**Comment by naithar** [comment]
Thanks! `thin` gave 3x speedup in building final app.
