### ISSUE TITLE
arm64 fails for building with iOS SDK

### ISSUE THREAD

**Issue by zatarus** [tpoechtrager/cctools-port#11]
I have gone through build for ios example.
At last part, test can not pass (using Ubuntu 14.04):

*** checking toolchain ***

clang: error: invalid arch name '-arch arm64'

Both tried with iOS SDK 8.3 and 8.4, perhaps it is a wrapper issue?

**Comment by dmigous** [comment]
@zatarus please provide more info about clang version and CFLAGS
if your clang version is less than 3.5 then if I remember right there is no support arm64 

also please read this issue https://github.com/tpoechtrager/cctools-port/issues/6#issuecomment-152952902

**Comment by zatarus** [comment]
@dmigous Just checked the version after you pointed out. It was because ubuntu 14 ships with clang 3.4, I have upgraded to 3.5 and everything works now. I appreciate the help.
