### ISSUE TITLE
debug builds

### ISSUE THREAD

**Issue by dmigous** [tpoechtrager/cctools-port#12]
When I tried to build debug builds with clang-3.5 it complained that cant find dsymutil. And back then I couldn't find dsymutil port for linux that will work for me. Now I discovered that clang-3.7 has some llvm-dsymutil, I made symlink /usr/bin/dsymutil => llvm-dsymutil

And now I am getting following error once any `-g` flag e.g `-g3`  present

```
vagrant@30a2df1550ea:/vagrant/target/ios/arm-apple-darwin/armv7/debug/ambrosia_adapters/tmp$ /vagrant/target/native/release/apple_cctools/arm-apple-darwin/usr/bin/arm-apple-darwin-clang -DHAVE_CONFIG_H  -miphoneos-version-min=7.1 -target arm-apple-darwin -arch armv7 -pipe -isysroot /home/vagrant/SDKs/iOS/iPhoneOS7.1.sdk -stdlib=libstdc++ -isystem /home/vagrant/SDKs/iOS/iPhoneOS7.1.sdk/usr/include/c++/4.2.1 -O0 -g ./conftest.c 
error: failed to compute relocation: ARM_RELOC_VANILLA
error: failed to compute relocation: ARM_RELOC_VANILLA
error: failed to compute relocation: ARM_RELOC_VANILLA
error: failed to compute relocation: ARM_RELOC_VANILLA
error: failed to compute relocation: ARM_RELOC_VANILLA
```

If somebody can help me, I'll be happy :-)

**Comment by dmigous** [comment]
@zatarus  @tpoechtrager any suggestions?

**Comment by tpoechtrager** [comment]
It seems like you aren't my build script, my build script installs a fake `dsymutil`.

Anyway, LLVM 3.7 isn't sufficient. Install dsymutil via https://github.com/tpoechtrager/llvm-dsymutil.

Follow https://github.com/tpoechtrager/osxcross/blob/master/build_llvm_dsymutil.sh - but install the tool as `dsymutil` (not `[osxcross-]llvm-dsymutil`).

No idea if this works iOS. I can't test this right now.

**Comment by dmigous** [comment]
@tpoechtrager thanks for response. I have another question that can't google.. 
So I built lib with debug flags. Seems now lib contains DWARF debug info. Now I want to ship this built lib to another developer and make him able to debug inside lib code. So to do that I have to send along with library the sources. But how to set in Xcode where to search sources while debugging? Maybe you know

**Comment by tpoechtrager** [comment]
Follow https://github.com/tpoechtrager/osxcross/blob/master/README.DEBUGGING.md and https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html

**Comment by dmigous** [comment]
@tpoechtrager thanks for the links

1. is only build with -g and .dSYM files enough to be able debug on another machine with ability step into code of my library?
2. In the latest link with specifying sources I guess  build with -g flag and setting sources path is enough, right?

So I can do one of above variants, correct?

**Comment by tpoechtrager** [comment]
Build the binary with `-g`, *after* linking run `dsymutil`. On the machine where you are doing the debugging you will need the `.dSYM` folder, the binary and the source code.

Please ask such questions on StackOverflow - you will get better answers there.

**Comment by dmigous** [comment]
does dsymutil work with archive libs?

```
/vagrant/base/osxcross/target/bin/../bin/osxcross-llvm-dsymutil ./libfoo.a
error: cannot parse the debug map for "./libfoo.a": The file was not recognized as a valid object file
```

but this libfoo.a certainly works on target device and built with -g

if dsymutil works well on .dylib may I use generated dSYM files with corresponding archive lib?

**Comment by tpoechtrager** [comment]
Quoting the `llvm-dsymutil` manual:

> dsymutil links the DWARF debug information found in the **object files**
> for the **executable** <input file> by using debug symbols information
> contained in its symbol table.

Thus, it makes no sense to run `dsymutil` on a static library. A static library is just a collection of object files.

**Comment by tpoechtrager** [comment]
I guess this can be closed?

**Comment by dmigous** [comment]
yes, thanks a lot for your help
