### ISSUE TITLE
cctools 986 & ld64 711 are available

### ISSUE THREAD

**Issue by dpogue** [tpoechtrager/cctools-port#134]
This is still not the most recent code, but Apple did finally publish the versions of cctools and ld64 that shipped with Xcode 13.0 back in September 2021:
* https://github.com/apple-oss-distributions/cctools/tree/cctools-986
* https://github.com/apple-oss-distributions/ld64/tree/ld64-711

**Comment by fanquake** [comment]
Note that there is a branch available now: https://github.com/tpoechtrager/cctools-port/tree/986-ld64-711.

**Comment by h-vetinari** [comment]
598995511c299feee4cd87f076ab9c53d5f80215 notes:
> Hasn't undergone a lot of testing so far.

Not sure what's (still) necessary for increased confidence?

**Comment by OldWorldOrdr** [comment]
I've been using it along with tapi 13 and it works great

**Comment by dpogue** [comment]
This seems to be the default branch now, so I'm going to mark this as done :)
