### ISSUE TITLE
build c++11 code

### ISSUE THREAD

**Issue by dmigous** [tpoechtrager/cctools-port#16]
Hello

I am trying to build c++11 code I am getting following errors:

```
/vagrant/target/native/release/apple_cctools/arm-apple-darwin/usr/bin/arm-apple-darwin-clang++ -DHAVE_CONFIG_H -I/vagrant/base/log4cplus/include -I/vagrant/base/log4cplus/threadpool -I./include -I/vagrant/base/log4cplus/catch/single_include -DCATCH_CONFIG_PREFIX_ALL=1 -DNDEBUG -DINSIDE_LOG4CPLUS -miphoneos-version-min=7.1 -target arm-apple-darwin -arch arm64 -pipe -isysroot /home/vagrant/SDKs/iOS/iPhoneOS7.1.sdk -stdlib=libstdc++ -I/home/vagrant/SDKs/iOS/iPhoneOS7.1.sdk/usr/include/c++/4.2.1 -D_GNU_SOURCE=1 -D_REENTRANT -I/home/vagrant/SDKs/iOS/iPhoneOS7.1.sdk/usr/include/c++/4.2.1 -std=gnu++11 -Wall -fdiagnostics-color=auto -Wextra -pedantic -Wstrict-aliasing -Wstrict-overflow -Woverloaded-virtual -Wold-style-cast -Wc++14-compat -Wundef -Wshadow -Wformat -Wno-variadic-macros -O2 -fvisibility=hidden -D_THREAD_SAFE -MT src/liblog4cplus_la-appender.lo -MD -MP -MF src/.deps/liblog4cplus_la-appender.Tpo -c /vagrant/base/log4cplus/src/appender.cxx  -fno-common -DPIC -o src/liblog4cplus_la-appender.o
...
/vagrant/base/log4cplus/include/log4cplus/tstring.h:71:17: error: no member named 'move' in namespace 'std'
    return std::move (str);
...
/vagrant/base/log4cplus/include/log4cplus/helpers/timehelper.h:40:10: fatal error: 'chrono' file not found
...

```

I am using clang 3.5, which supports c++11

```
ls -l /vagrant/target/native/release/apple_cctools/arm-apple-darwin/usr/bin/arm-apple-darwin-clang++
lrwxrwxrwx. 1 vagrant vagrant 20 Dec 16 07:55 /vagrant/target/native/release/apple_cctools/arm-apple-darwin/usr/bin/arm-apple-darwin-clang++ -> /usr/bin/clang++-3.5

```

Maybe someone encountered the similar issue?

**Comment by tpoechtrager** [comment]
Use `-stdlib=libc++` instead of `-std=libstdc++`. Also, please stop posting
SDK download links.

2015-12-16 9:27 GMT+01:00 dmigous <notifications@github.com>:

**Comment by dmigous** [comment]
sorry, just wanted to be clear what I use, because am not directly downloaded it from apple site. I can remove link, should I?

**Comment by tpoechtrager** [comment]
I removed the link. I don't want SDK dowload links to be posted here.

**Comment by dmigous** [comment]
Anyway change to `-std=libc++` doesn't resolve issue.  It still can't find `chrono` file. 

I did search chrono file in iPhone SDK folder and nothing there... But then I searched in MacOS SDK folder at osxcross project for `chrono` file, and it is at `MacOSX10.11.sdk/usr/include/c++/v1/chrono`, while in iPhone sdk folder there is no `iPhoneOS7.1.sdk/usr/include/c++/v1/` folder, just `iPhoneOS7.1.sdk/usr/include/c++/4.2.1`.

**Comment by tpoechtrager** [comment]
Your SDK is broken. Follow https://github.com/tpoechtrager/osxcross/issues/45#issuecomment-138351002 to create a proper SDK.
