### ISSUE TITLE
Missing "openssl/err.h" after runing build.sh

### ISSUE THREAD

**Issue by xiaozhi** [tpoechtrager/cctools-port#17]
After i running `./build.sh iPhone9.2.sdk.tar.xz arm7`,error is
```
ldid.cpp:46:25: fatal error: openssl/err.h: No such file or directory
 #include <openssl/err.h>
```

also I get sdk from [#45](https://github.com/tpoechtrager/osxcross/issues/45#issuecomment-138351002)

I need some help ,Think you very much

**Comment by xiaozhi** [comment]
Also ,can cctools-port export ipa?

**Comment by tpoechtrager** [comment]
> `ldid.cpp:46:25: fatal error: openssl/err.h: No such file or directory`

You must install `libressl-dev`, see `usage_examples/ios_toolchain/README`.

> Also ,can cctools-port export ipa?

No.

**Comment by xiaozhi** [comment]
@tpoechtrager OK, Think you
