### ISSUE TITLE
SDK version 10.0 and up not noticed by build.sh

### ISSUE THREAD

**Issue by SimonSuckut** [tpoechtrager/cctools-port#23]
change the line where the SDK-Version is read from the archive name to:
SDK_VERSION=$(echo $1 | grep -P -o "[0-9][0-9].[0-9]+" | head -1)
if [ -z "$SDK_VERSION" ]; then
    SDK_VERSION=$(echo $1 | grep -P -o "[0-9].[0-9]+" | head -1)
    if [ -z "$SDK_VERSION" ]; then
            echo "iPhoneOS Version must be in the SDK filename!" 1>&2
            exit 1
    fi
fi (there is surely a better way to do this, I am not very familiar with sh scripts)
 or something similar so that version 10.0 and up are noticed by the script.

**Comment by tpoechtrager** [comment]
Works for me without the need to change anything.

What does `grep --version` print?

**Comment by SimonSuckut** [comment]
Hi,

My grep version is 2.25 on ubuntu 16.04. The script detects SDK Version 
0.0 if I use the iPhoneSDK10.0.sdk. The build process works of course, 
but the macro in wraper.c is not defined correctly. As a result the 
min-sdk-version is wrong.

But there is another problem. Apple changed the library format in SDK 
version 10. These libraries are only usable with ld64-274. But the 
newest version on ld64 that is open source is version 264. Do you have a 
workaround for this problem? I have used iPhoneSDK10 which I extracted 
from an XCode8.dmg and wrote a little script that changes the XSym-links 
to standard symbolic links. With SDK 9.3 everything works perfect. The 
script looks like this (feel free to use/include it):

#!/bin/bash

for d in $(find $1 -maxdepth 10 -type d)
do
         for f in $(find $d -maxdepth 1 -type f)
                 do
                         HEAD=$(head -c 4 "$f")
                         if [ "$HEAD" == "XSym" ]; then
                         DEST=$(sed '4q;d' $f)
                         echo "Dest: $DEST"
                         rm -r $f
                         ln -s "$DEST" "$f"
                 fi
         done
done


Best requards Simon



Am 21.10.2016 um 22:47 schrieb Thomas Pöchtrager:

**Comment by tpoechtrager** [comment]
`-mios-version-version=10.0` is wrong?

And no, I don't have a workaround for the linker issues. I will update `build.sh` once we have an appropriate linker.

**Comment by SimonSuckut** [comment]
Sry if it was a little bit confusing what i wrote. The build.sh script
reads the SDK_Version from the filename. In my case it reads version 0.0 if
i use a sdk10.0.gar.gz ("echo $SDK_VERSION" prints "0.0"). The reason for
that are the 2 digits before the dot in the number. The script expects only
one. The script then passes the wrong $SDK_VERSION as OS_VER_MIN when
wraper.c gets compiled.

This line then sets version "0.0" as the default "iphoneos-version-min":
env(&osmin, "IPHONEOS_DEPLOYMENT_TARGET", OS_VER_MIN);
Of course the problem does not exist if you define
"IPHONEOS_DEPLOYMENT_TARGET" before you build something with the toolchain.

I hope that discribes the problem better.

Best reguards Simon

Am 28.10.2016 15:12 schrieb "Thomas Pöchtrager" <notifications@github.com>:

**Comment by tpoechtrager** [comment]
Oh, I see.

Well, `-mios-version-min=10.0` isn't working either...

    $ clang -target arm64-apple-darwin11 -mios-version-min=10.0 ~/tmp/test.c
    clang-3.9: error: invalid version number in '-miphoneos-version-min=10.0'
    $ clang -target arm64-apple-darwin11 -miphoneos-version-min=10.0 ~/tmp/test.c
    clang-3.9: error: invalid version number in '-miphoneos-version-min=10.0'


Annoying.

**Comment by SimonSuckut** [comment]
Yes, that's another problem. I am not so familiar with the IOS SDK but i
think that it has to do with the lib file format or the linker version.
ld64-264 is not made for a SDK version higher than 9.3. (it might also not
accept numbers with more then 2 digits in front of the dot)

Best reguards Simon

Am 29.10.2016 18:30 schrieb "Thomas Pöchtrager" <notifications@github.com>:

**Comment by tpoechtrager** [comment]
Yes, ld64-264 does not support the new v2 text stubs. We have to wait until Apple releases the sources for the new lnker. Unfortunately, I have no idea when that will happen.
