### ISSUE TITLE
The 'unknown-apple-darwin' addition breaks things on Darwin

### ISSUE THREAD

**Issue by copumpkin** [tpoechtrager/cctools-port#24]
It looks like you add a `-target unknown-apple-darwin` argument to the assembler invocation. Not sure quite which circumstances trigger it, but if I patch out your patch, that fixes https://github.com/NixOS/nixpkgs/issues/17759 for me.

https://github.com/tpoechtrager/cctools-port/blob/cctools-877.8-ld64-253.9-1/cctools/as/driver.c#L369

**Comment by tpoechtrager** [comment]
This happens when `-arch <arch>` isn't passed to the assembler.

Should be fixed.

**Comment by copumpkin** [comment]
Cool, yeah, I have some Apple builds that expect to be able to call `as` without a target with reasonable results (presumably same as host). Thanks for the quick fix here too!

**Comment by tpoechtrager** [comment]
You are welcome, and thanks for the bug reports!

I would have probably never noticed these issues by myself...
