### ISSUE TITLE
Apple finally released source for 10.12(.1)!

### ISSUE THREAD

**Issue by copumpkin** [tpoechtrager/cctools-port#27]
That means we now have cctools-895 and ld64-274.1. Just FYI, not in any sort of rush to get it 😄

**Comment by tpoechtrager** [comment]
It looks like they made the text stub stuff proprietary? At least I can't find the sources for the tapi library.

**Comment by copumpkin** [comment]
I think the generally recommended practice is to file a radar with them asking for a TAPI release. I hear if enough of us do it, it might go somewhere, but I'm not very hopeful. We might need to hack the old stuff into the newer code if they don't do it 😦

**Comment by jeremyhu** [comment]
@copumpkin I already did that in MacPorts.  See https://github.com/macports/macports-ports/tree/master/devel/ld64

Regarding TAPIv2, please do file a radar and point me to it.  It'll get duped to the one I filed, but the more dupes I have attached to it, the better.  Thanks.

**Comment by jeremyhu** [comment]
Ah, I see you already did, thanks.

**Comment by tpoechtrager** [comment]
@jeremyhu: Awesome! Am I allowed to use your patches?

**Comment by tpoechtrager** [comment]
@jeremyhu: Ping.

**Comment by jeremyhu** [comment]
@tpoechtrager Sorry I missed that.  Of course, you're certainly free to use them.  The patches are licensed under the same license as ld64 itself (APSL-2).

**Comment by tpoechtrager** [comment]
@copumpkin: Merged cctools 895 and ld64 274.2. Sorry for the long delay.

**Comment by copumpkin** [comment]
No problem, thanks!!

**Comment by andsveking** [comment]
Just ran into the issue with `ld: unexpected token: !tapi-tbd-v2`. :) Do you happen to have link for any bug report (or openradar) that you filed?

**Comment by tpoechtrager** [comment]
@andsveking: The TAPI library [is already open source](https://opensource.apple.com/tarballs/tapi). TAPIv2 support will be added to cctools-port within the next few days.

**Comment by andsveking** [comment]
Fantastic! 🏆

**Comment by hszcg** [comment]
@tpoechtrager could you please help TAPIv2? or if there any way I could contribute to it?

thanks,

**Comment by DuIslingr** [comment]
@tpoechtrager bump on that tapi support?

**Comment by tpoechtrager** [comment]
@andsveking @hszcg @DuIslingr Sorry, I can't work on cctools-port at the moment.

I have created a (wip) test branch. If you want to give it a try: https://github.com/tpoechtrager/cctools-port/tree/895-ld64-274.2-tapiv2

**Comment by tpoechtrager** [comment]
TAPIv2 support should be "complete" now.

**Comment by copumpkin** [comment]
Thanks!!

**Comment by hszcg** [comment]
@tpoechtrager thx!

**Comment by andsveking** [comment]
Awesome! 😍
