### ISSUE TITLE
Are feature PRs accepted? I'd like to normalize and print CLI args

### ISSUE THREAD

**Issue by Ericson2314** [tpoechtrager/cctools-port#32]
I wrote this script https://github.com/NixOS/nixpkgs/blob/6d4bd78fad1c2040cafe6f5fa30d8134dac3bdf6/pkgs/build-support/cc-wrapper/macos-sierra-reexport-hack.bash to squeeze under macOS Sierra's artificial header size limit. It uses `-reexport-l` to divide and conquer the list of linker inputs, creating a binary tree of delegated reexporting libraries so that none has a header over the limit.

The problem is it breaks down if some `-l...` would be resolved to a static archive instead. I could fix that in bash, but at some points it becomes silly to reimplement https://github.com/tpoechtrager/cctools-port/blob/master/cctools/ld64/src/ld/Options.cpp. It would be much easier to assume absolute paths for all linker inputs, and divide and conquer on that.

If new non-apple features are accepted, I'd like to add a flag to just resolve libraries, and spit out all flags in a normal form (not doing any actually linking). I can then run my script on that output, satisfying my convenient assumption above.

CC @copumpkin @shlevy

**Comment by tpoechtrager** [comment]
Yes, of course. If you want me to I can grant you write access to this repository so you can commit this yourself.

**Comment by Ericson2314** [comment]
@tpoechtrager Thanks so much! I'm fine either way, so whatever you prefer :).

**Comment by tpoechtrager** [comment]
I added you as a collaborator. I think you must still accept the invitation here: https://github.com/tpoechtrager/cctools-port/invitations.

**Comment by Ericson2314** [comment]
I just did, thanks again!
