### ISSUE TITLE
error:CentOS use clang5.0 

### ISSUE THREAD

**Issue by heroims** [tpoechtrager/cctools-port#33]
[lookfe@troy ios_toolchain]$ ./build.sh ~/testIOS/iPhoneOS10.3.sdk.tar.gz armv7
......
......
[ 73%] Built target LLVMMCParser
[ 73%] Linking CXX static library ../libLLVMMC.a
warning: /usr/local/bin/ranlib: warning for library: ../libLLVMMC.a the table of contents is empty (no object file members in the library define global symbols)
[ 73%] Built target LLVMMC
[ 73%] Built target obj.llvm-tblgen
[ 73%] Linking CXX static library ../libLLVMSupport.a
warning: /usr/local/bin/ranlib: warning for library: ../libLLVMSupport.a the table of contents is empty (no object file members in the library define global symbols)
[ 73%] Built target LLVMSupport
Scanning dependencies of target llvm-tblgen
[ 73%] Linking CXX executable ../../bin/llvm-tblgen
......
......
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/llvm-tblgen] Error 1
make[2]: *** [utils/TableGen/CMakeFiles/llvm-tblgen.dir/all] Error 2
make[1]: *** [projects/libtapi/tools/libtapi/CMakeFiles/libtapi.dir/rule] Error 2
make: *** [libtapi] Error 2

**Comment by tpoechtrager** [comment]
Need the whole build log. If this is no longer an issue, please close this.
