### ISSUE TITLE
cannot invoke compiler!

### ISSUE THREAD

**Issue by CJxD** [tpoechtrager/cctools-port#38]
I've just successfully built the ios_toolchain with the iPhoneSDK from Xcode 9.1 following this tutorial: http://docs.godotengine.org/en/stable/development/compiling/cross-compiling_for_ios_on_linux.html

However, after finishing, I get a `cannot invoke compiler!`.

The MD5 of my iPhoneOS9.1.sdk.tar.xz file is `73f09280e41efb6b4583fab53cc7787b`

Built with `~/manual-software/cctools-port/usage_examples/ios_toolchain$ ./build.sh ~/manual-software/iPhoneSDK/iPhoneOS9.1.sdk.tar.xz armv7`

[build.log](https://github.com/tpoechtrager/cctools-port/files/1456026/build.log)

**Comment by tpoechtrager** [comment]
It looks like you do not have Clang installed.

**Comment by CJxD** [comment]
Thanks for the reply. That was indeed the issue. For me, the command for clang is `clang-3.5`, so I just added a symlink `ln -s /usr/bin/clang-3.5 /usr/bin/clang`
