### ISSUE TITLE
ld: library not found for -lSystem

### ISSUE THREAD

**Issue by 871699406** [tpoechtrager/cctools-port#39]
Determining if the C compiler works failed with the following output:
Change Dir: /ncnn/ncnn/build-ios/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_7236a/fast"
/usr/bin/make -f CMakeFiles/cmTC_7236a.dir/build.make CMakeFiles/cmTC_7236a.dir/build
make[1]: Entering directory `/ncnn/ncnn/build-ios/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_7236a.dir/testCCompiler.c.o
/ncnn/cctools-port/usage_examples/ios_toolchain/target/bin/arm-apple-darwin11-clang   -arch armv7 -arch arm64 -isysroot /ncnn/cctools-port/usage_examples/ios_toolchain/target/SDK   -o CMakeFiles/cmTC_7236a.dir/testCCompiler.c.o   -c /ncnn/ncnn/build-ios/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_7236a
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7236a.dir/link.txt --verbose=1
/ncnn/cctools-port/usage_examples/ios_toolchain/target/bin/arm-apple-darwin11-clang   -arch armv7 -arch arm64 -isysroot /ncnn/cctools-port/usage_examples/ios_toolchain/target/SDK -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_7236a.dir/testCCompiler.c.o  -o cmTC_7236a
ld: library not found for -lSystem
clang-3.8: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_7236a] Error 1
make[1]: Leaving directory `/ncnn/ncnn/build-ios/CMakeFiles/CMakeTmp'
make: *** [cmTC_7236a/fast] Error 2

above is my CMakeError.log  it seems cant find libSystem
when I search libSystem ,i found it in cctools-port/usage_examples/ios_toolchain/target/SDK/iPhoneOS9.1.sdk/usr/lib/libSystem.tbd
how can I solve this bug?

**Comment by 871699406** [comment]
![qq 20171120170358](https://user-images.githubusercontent.com/8012818/33010491-a3b8601c-ce15-11e7-9ce2-c8bbc1692f37.jpg)
![qq 20171120170945](https://user-images.githubusercontent.com/8012818/33010492-a4076f18-ce15-11e7-9be9-c8f6267bc1a7.jpg)
also ,I came across that clang is broken when I do cross-compile ,any advice?

**Comment by 871699406** [comment]
I found the reason.The path in my toolchain file is wrong.

**Comment by tpoechtrager** [comment]
Glad you found a solution! Please close this if this no longer an issue.
