### ISSUE TITLE
Can man pages be built by default?

### ISSUE THREAD

**Issue by Ericson2314** [tpoechtrager/cctools-port#40]
I see the comment at https://github.com/tpoechtrager/cctools-port/blob/c1cc75893ed1978174fdcd1b898f81e6535e82d3/cctools/configure.ac#L408

What needs to be fixed?

Also, I gather the ld manpage is elsewhere; I don't see it getting produced either.

**Comment by matthewbauer** [comment]
Maybe make a PR? We can add it as a patch in Nixpkgs if it's not accepted.

**Comment by tpoechtrager** [comment]
A PR would be more than welcome if it works on all supported OSs.

**Comment by matthewbauer** [comment]
Done in #61

**Comment by Ericson2314** [comment]
Sweet!
