### ISSUE TITLE
IOS11 SDK problem

### ISSUE THREAD

**Issue by fanyunfei786452470** [tpoechtrager/cctools-port#41]
On Linux llvm5.0 and clang5.0, generate iOS tool chain.
I did this：
$ IPHONEOS_DEPLOYMENT_TARGET=5.0 usage_examples/ios_toolchain/build.sh ~/iPhoneSDK/iPhoneOS11.1.sdk.tar.gz arm64

The result is as follows：
error: unable to create target: 'No available targets are compatible with this triple.' 1 error generated.

**Comment by tpoechtrager** [comment]
You must build LLVM/Clang with the ARM/AARCH64 backend enabled. What distribution are you on? Did you build LLVM/Clang yourself?

**Comment by fanyunfei786452470** [comment]
I download llvm5.0 and clang5.0 source on http://releases.llvm.org/download.html#4.0.0, and then compiled on Linux and compiling ways: cmake../ LLVM - DLLVM_TARGETS_TO_BUILD = X86  DCMAKE_BUILD_TYPE = Release, the result is: cctools - port error: unable to create a target: 'No available targets are compatible with this triple.' 1 error generated.

**Comment by fanyunfei786452470** [comment]
In Ubuntu16.04 LTS,
Clang version 5.0.0 (tags/RELEASE_500 / final)
Target: x86_64 - unknown - Linux - gnuThe 
Thread model: posixInstalledDir: / usr/local/bin
LLVM version 5.0.0
Optimized build.
The Default target: x86_64 - unknown - Linux - gnu
But, I don't know how to set the ARM/AArch64 backend on Ubuntu, what should I do?

**Comment by tpoechtrager** [comment]
Try:

    cmake .. -DLLVM_ENABLE_ASSERTIONS=OFF -DCMAKE_BUILD_TYPE=RELEASE

**Comment by fanyunfei786452470** [comment]
Thank you very much for your answer, my problem has been solved according to your answer

**Comment by tpoechtrager** [comment]
You are welcome. Glad you got it working!
