### ISSUE TITLE
ld can't find libtapi.so

### ISSUE THREAD

**Issue by rraallvv** [tpoechtrager/cctools-port#42]
While cross-compiling for iOS on Linux I get the following error:

> /home/travis/ioscross-target/usr/bin/arm-apple-darwin11-clang++ -o bin/godot.iphone.debug.arm -arch armv7 -Wl,-dead_strip -miphoneos-version-min=7.0 -isysroot /home/travis/ioscross-target/target/SDK/iPhoneOS9.3.sdk -framework Foundation -framework UIKit -framework CoreGraphics -framework OpenGLES -framework QuartzCore -framework CoreAudio -framework AudioToolbox -framework SystemConfiguration -framework Security -framework MediaPlayer -framework AVFoundation -framework CoreMedia -framework CoreMotion -framework GameController -framework GameKit -framework StoreKit -Wl,-rpath-link,/home/travis/ioscross-target/target/lib -Wl,--rpath-link /home/travis/ioscross-target/target/lib -L/home/travis/ioscross-target/target/lib platform/iphone/godot_iphone.iphone.debug.arm.o platform/iphone/os_iphone.iphone.debug.arm.o platform/iphone/audio_driver_iphone.iphone.debug.arm.o platform/iphone/sem_iphone.iphone.debug.arm.o platform/iphone/gl_view.iphone.debug.arm.o platform/iphone/main.iphone.debug.arm.o platform/iphone/app_delegate.iphone.debug.arm.o platform/iphone/view_controller.iphone.debug.arm.o platform/iphone/game_center.iphone.debug.arm.o platform/iphone/in_app_store.iphone.debug.arm.o platform/iphone/icloud.iphone.debug.arm.o platform/iphone/ios.iphone.debug.arm.o -L/home/travis/ioscross-target/target/lib main/libmain.iphone.debug.arm.a main/tests/libtests.iphone.debug.arm.a modules/libmodules.iphone.debug.arm.a drivers/libdrivers.iphone.debug.arm.a scene/libscene.iphone.debug.arm.a servers/libservers.iphone.debug.arm.a core/libcore.iphone.debug.arm.a modules/freetype/libfreetype_builtin.iphone.debug.arm.a
> /home/travis/ioscross-target/usr/bin/arm-apple-darwin11-ld: error while loading shared libraries: libtapi.so: cannot open shared object file: No such file or directory
> clang-3.9: error: unable to execute command: No such file or directory
> clang-3.9: error: linker command failed due to signal (use -v to see invocation)
> scons: *** [bin/godot.iphone.debug.arm] Error 255
> scons: building terminated because of errors.

I think Scons is not executing ld but maybe it's being invoked by clang itself. I tried passing `-Wl,-rpath-link` and exporting `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH` with the path to `libtapi.so` but I'm still getting the error.

Where is ld searching for shared libraries on Linux and how can I add a custom path to the search list?

**Comment by tpoechtrager** [comment]
`LD_LIBRARY_PATH` is correct. i.e.: `export LD_LIBRARY_PATH=/usr/local/lib`

**Comment by rraallvv** [comment]
@tpoechtrager thanks!
