### ISSUE TITLE
Toolchain points to the wrong ldid executable

### ISSUE THREAD

**Issue by darmie** [tpoechtrager/cctools-port#45]
How do I fix this? 
Toolchain is trying to use the `ldid.exe` that came along with cygwin64, do you have any idea how I can correct this?

```
      6 [main] ldid (12968) C:\cygwin64\bin\ldid.exe: *** fatal error - cygheap base mismatch detected - 0x1802F3408/0x180304408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```

**Comment by darmie** [comment]
After exporting the built executables to PATH, I am getting this error

```
$ arm-apple-darwin11-clang test.c -arch armv7
error: unable to create target: 'No available targets are compatible with this triple.'
1 error generated.
```
Isn't Clang 5.0 supposed to solve this problem?

**Comment by tpoechtrager** [comment]
You are still using an LLVM/Clang version without ARM support enabled. Dunno about the other error. ld64 is probably picking up the wrong ldid executable.

**Comment by darmie** [comment]
I rebuilt LLVM/Clang 5.0 which I presume has ARM support. I don't know what I am doing wrong.

**Comment by tpoechtrager** [comment]
Post the build parameters.

**Comment by darmie** [comment]
For LLVM/Clang ?

**Comment by darmie** [comment]
Fixed. Uninstalled previous versions of LLVM and Clang.

**Comment by tpoechtrager** [comment]
So everything works now?

**Comment by darmie** [comment]
Yes. Thanks
