### ISSUE TITLE
Problem while building on MacOS

### ISSUE THREAD

**Issue by Chensiyang** [tpoechtrager/cctools-port#54]
I attempt to build cctools for my iOS Application supporting OpenMP feature.

  1、install llvm-6.0.1 from brew (brew install llvm)
  2、download cctools-port from git and extract
  3、simply run "IPHONEOS_DEPLOYMENT_TARGET=8.0 JOBS=4 usage_examples/ios_toolchain/build.sh ~/iPhoneOS11.0.sdk.tar.gz armv7"

After solving a little bit problem，when building apple-libtapi，i got warnings when finished:

  ld: warning: cannot export hidden symbol void  tapi::v1::LinkerInterfaceFile::Impl::addSymbol<tapi::v1::Symbol>(tapi::v1::Symbol&&, tapi::v1::PackedVersion32) from CMakeFiles/libtapi.dir/LinkerInterfaceFile.cpp.o
ld: warning: cannot export hidden symbol tapi::v1::LinkerInterfaceFile::Impl::~Impl() from CMakeFiles/libtapi.dir/LinkerInterfaceFile.cpp.o

and then when building cctools，it occurs:

  ld: warning: directory not found for option '-L/usr/pkg/lib'
make[3]: Nothing to be done for 'all-am'
make[2]: Nothing to be done for 'all-am'
make[1]: Nothing to be done for 'all-am'

macOS High Sierra,Xcode9.4.1 ,llvm-6.0.1.  Somebody help...

By the way,it is really a great job

**Comment by tpoechtrager** [comment]
Is it an error or just a warning?

**Comment by Chensiyang** [comment]
Hello tpoechtrager,I would rather say its warning messages.And today afternoon, I just ignore all these and try the output clang to compile a simple c file. All seems ok expect getting the message:
ldid:command not found

**Comment by Chensiyang** [comment]
Sorry guys,the message 
ldid:command not found
 just because I forget to export the "path/to/bin" to system search path just like what I haved did on an Ubuntu Machine Before.
Thanks tpoechtrager.
I would try this clang on Xcode to make iOS compile job,.

**Comment by tpoechtrager** [comment]
No problem. You are welcome. :-)
