### ISSUE TITLE
About the IOS toolchain build.sh 

### ISSUE THREAD

**Issue by arshiyasoleimani** [tpoechtrager/cctools-port#55]
I get this error when it starts to check the toolchain:

ld: file too small (length=15) file '/opt/theos/toolchain/linux/iphone/bin/cctools-port/usage_examples/ios_toolchain/target/bin/../SDK/iPhoneOS10.3.sdk/usr/lib/libSystem.tbd' for architecture arm64
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tpoechtrager** [comment]
The symlinks in your SDK are broken.
