### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by dmigous** [tpoechtrager/cctools-port#6]
I am trying to build cctools for arm64 under Fedora Linux

./configure --target=arm64-apple-darwin
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... Invalid configuration `arm64-apple-darwin': machine `arm64-apple' not recognized
configure: error: /bin/sh ./config.sub arm64-apple-darwin failed

Maybe you know what can cause this issue?

**Comment by dmigous** [comment]
this issue were solved by using for `-target` flag just `arm-apple-darwin` and for `-arch` flag `arm64`. Hence my CFLAGS appended with following for armv7, armv7s, arm64 correspondingly

```bash
CFLAGS += -target arm-apple-darwin -arch armv7
CFLAGS += -target arm-apple-darwin -arch armv7s
CFLAGS += -target arm-apple-darwin -arch arm64
```

**Comment by rennhak** [comment]
Nice, thanks dmigous! :)

**Comment by jau88** [comment]
You could use this too.

echo 'echo arm-apple-darwin' > config.sub
