### ISSUE TITLE
cctools-port error (iOS)

### ISSUE THREAD

**Issue by The-SamminAter** [tpoechtrager/cctools-port#72]
When I enter `    [--with-llvm-config=...]`, I get this error: 
`-sh: target: No such file or directory`

Terminal output for reference;
```
iPhone:/var/mobile/Library/Jailbreakappstbdp root# git clone https://github.com/tpoechtrager/cctools-port.git cctools-port/
done.
iPhone:/var/mobile/Library/Jailbreakappstbdp root# cd cctools-port/cctools
iPhone:/var/mobile/Library/Jailbreakappstbdp/cctools-port/cctools root# ./configure \
>     [--prefix=/home/user/cctools] \
>     [--with-libtapi=/home/user/cctools] \
>     [--target=<target>] \
>     [--with-llvm-config=...]
-sh: target: No such file or directory
```

**Comment by nathan-fiscaletti** [comment]
You have a fundamental misunderstanding of how one should parse information from github documentation. The `<>` symbols wrapping a particular word indicate that you should replace them with the desired value that the word represents. For example `<target>` means `<replace this with the target>`, for which a valid value might be `aarch64-apple-ios-eabi` or another triplet.

Additionally, the `[]` symbols wrapping each line indicate that the line is optional.

**Comment by The-SamminAter** [comment]
> You have a fundamental misunderstanding of how one should parse information from github documentation. The `<>` symbols wrapping a particular word indicate that you should replace them with the desired value that the word represents. For example `<target>` means `<replace this with the target>`, for which a valid value might be `aarch64-apple-ios-eabi` or another triplet.
> 
> 
> 
> Additionally, the `[]` symbols wrapping each line indicate that the line is optional.

Sorry, I know that know, had completely forgotten about this, and what I was even doing with it in the first place. I'm closing the issue, as there is no issue.
