### ISSUE TITLE
clang-10: error invalid arch name '-arch arm64e'

### ISSUE THREAD

**Issue by okanon** [tpoechtrager/cctools-port#75]
Attempting to define arm64e as an architecture will result in an error.
I am building using iPhoneOS13.2.sdk. Why do I get this problem?

**Comment by tpoechtrager** [comment]
Not supported by upstream Clang, I suppose.

**Comment by tpoechtrager** [comment]
https://github.com/apple/llvm-project/pull/14

**Comment by okanon** [comment]
Should I build and use clang for [this project](https://github.com/apple/llvm-project/pull/14)?

**Comment by tpoechtrager** [comment]
You could give it a try. I haven't tested it.

**Comment by okanon** [comment]
I built [apple/llvm-project master](https://github.com/apple/llvm-project) yesterday and tried building cctools with arm64e option. but, An error was raised indicating that the architecture is not supported.

**Comment by okanon** [comment]
I feel that [apple-libtapi](https://github.com/tpoechtrager/apple-libtapi) does not support arm64e. Is there any relevance?

```
-- TAPI version: 10.0.0
-- Supported Architectures: i386;x86_64;x86_64h;armv4t;armv6;armv5;armv7;armv7s;armv7k;armv6m;armv7m;armv7em;arm64
```

**Comment by tpoechtrager** [comment]
It's not the TAPI library, it's the linker. There's something missing.

    $ grep -rn "\"arm64\""
    src/abstraction/MachOFileAbstraction.hpp:669:   { "arm64", CPU_TYPE_ARM64,   CPU_SUBTYPE_ARM64_ALL,  "arm64-",  "aarch64-",  true,  false },
    src/ld/parsers/macho_relocatable_file.cpp:1449: return "arm64";
    src/ld/parsers/macho_dylib_file.cpp:774:  return "arm64";
    src/other/machochecker.cpp:353:                 return "arm64";
    src/other/unwinddump.cpp:103:template <>         const char*    UnwindPrinter<arm64>::archName()        { return "arm64"; }
    src/other/unwinddump.cpp:1173:                                  else if ( strcmp(arch, "arm64") == 0 )

Maybe you can get it working by adding arm64e to the array. But I can't promise anything. The code is missing in the sources Apple provided.

**Comment by okanon** [comment]
okay:cry:

**Comment by tpoechtrager** [comment]
Should be working now.
