### ISSUE TITLE
arm64e display not support.

### ISSUE THREAD

**Issue by okanon** [tpoechtrager/cctools-port#77]
It seems that support for arm64e has been substantially completed, but it is not supported on the display by the file command.
```
arm-apple-darwin11-clang -arch arm64e -o hello hello.c
file hello
hello: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```
```
# iPhone7 Plus iOS11.2 jailbroken (arm64)
sudo ldid -Sent.xml hello && sudo mv hello /usr/bin/
hello
Bad CPU type in executable
```

**Comment by tpoechtrager** [comment]
What is this issue about? I don't know what "display not support" might mean.

**Comment by okanon** [comment]
Sorry, the correction of the answer was delayed.
Is it normal for arm64e-compatible binaries to be written as arm64?

**Comment by tpoechtrager** [comment]
I don't think iOS11.2 supports arm64e.

**Comment by okanon** [comment]
I know that, does arm64e binaries still show arm64?

**Comment by tpoechtrager** [comment]
The `file` command does not support arm64e.

    otool -L a.out 
    a.out (architecture armv6):
            /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
    a.out (architecture armv7):
            /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
    a.out (architecture armv7s):
            /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
    a.out (architecture arm64):
            /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
    a.out (architecture arm64e):
            /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)

**Comment by okanon** [comment]
Mystery was solved. Thank you :)

**Comment by tpoechtrager** [comment]
👍
