### ISSUE TITLE
Building for IOS error

### ISSUE THREAD

**Issue by macalimlim** [tpoechtrager/cctools-port#78]
I tried to build cctools-port by executing this command `./build.sh /path/to/iPhoneOS9.2.sdk.tar.xz arm64`. But I keep getting this error `You must compile this project with clang. Other compilers are no longer supported.`. I do have clang version 7.1.0 installed. I also tried to use clang version 8, same error. Can someone help me in doing this? Thanks :)

**Comment by tpoechtrager** [comment]
Unset CC, CXX environment variables.

Michael Angelo Calimlim <notifications@github.com> schrieb am Do., 30. Jän.
2020, 04:24:

**Comment by macalimlim** [comment]
Great! it now works, thanks :)
