### ISSUE TITLE
openssl issue while build iOS tool chain

### ISSUE THREAD

**Issue by Dayananda87** [tpoechtrager/cctools-port#79]
I got below erros while build iOS tool chain
`cctools$ ./configure --prefix=<path>/cctools --with-libtapi=<path>/cctools`
`cctools$ make`

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Makefile:460: recipe for target 'libstuff_la-arch.lo' failed
make[1]: *** [libstuff_la-arch.lo] Error 1
make[1]: Leaving directory '/mnt/hdd/opt/code/x-compiler/cctools-port/cctools/libstuff'
Makefile:416: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

Please help me with above issue.

**Comment by Dayananda87** [comment]
I also got below error while `cctools$ make`

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Makefile:460: recipe for target 'libstuff_la-arch.lo' failed
make[1]: *** [libstuff_la-arch.lo] Error 1
make[1]: Leaving directory '/mnt/hdd/opt/code/x-compiler/cctools-port/cctools/libstuff'
Makefile:416: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

**Comment by Dayananda87** [comment]
Once i remove `--with-libtapi` arg and proceed with just `./configure --prefix=/opt/code/x-compiler/cctools-port/cctools` && `make && make install` everything works.

But, `./build.sh iPhoneOS13.2.sdk.tar.gz arm64` fails with below error.

`ldid.cpp:46:10: fatal error: openssl/err.h: No such file or directory
 #include <openssl/err.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:27: recipe for target 'ldid.o' failed
make: *** [ldid.o] Error 1
make: *** Waiting for unfinished jobs....`

**Comment by tpoechtrager** [comment]
Install the OpenSSL library.

**Comment by Dayananda87** [comment]
@tpoechtrager, Thanks for the quick turn around.
I'm using Ubuntu 18.0. Sure I will install and let you know.
I hope `libssl-devel` is the library.

Thanks,
Dayananda

**Comment by Dayananda87** [comment]
Hi @tpoechtrager ,

Installed `libssl-devel` and ran 
./configure --prefix=<path>/cctools `worked fine`
make && make install `worked fine`

but ./build <sdk.tar.gz> <target> threw below error

`clang: warning: no such sysroot directory: '/mnt/hdd/opt/code/x-compiler/cctools-port/usage_examples/ios_toolchain/target/bin/../SDK/iPhoneOS*sdk' [-Wmissing-sysroot]
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Thanks,
Dayanand

**Comment by tpoechtrager** [comment]
Good - one step further. :-)

Undo the changes you did to build.sh. The TAPI library is required for
newer SDKs.

Dayanand <notifications@github.com> schrieb am Mo., 2. März 2020, 22:07:

**Comment by Dayananda87** [comment]
Ok cool!, I will try that again 👍 
Thanks for your time and patience.

**Comment by Dayananda87** [comment]
It worked fine now. Thanks a lot once again.
I'm closing this issue now.
