### ISSUE TITLE
Compilation of xar

### ISSUE THREAD

**Issue by demhademha** [tpoechtrager/cctools-port#83]
Hi, I don't know if you'll be able to help as the xar project linked here is dead. 
However, on Linux when typing ./autogen.sh , for the compilation of xar, it is unable to build without OpenSSL, however, I have the latest version.   
Error log:

checking openssl/evp.h presence... yes
checking for openssl/evp.h... yes
checking for OpenSSL_add_all_ciphers in -lcrypto... no
configure: error: Cannot build without libcrypto (OpenSSL)
Error 0 in ./configure

any support would be appreciated

**Comment by tpoechtrager** [comment]
I fixed some of the issues here: https://github.com/tpoechtrager/xar

**Comment by demhademha** [comment]
Hi, I think it'd be better to direct people to here rather than the outdated xar. 
I'll make a pr shortly
