### ISSUE TITLE
fatal error: as: unknown host architecture (can't determine which assembler to run)

### ISSUE THREAD

**Issue by djeraseit** [tpoechtrager/cctools-port#87]
Installing this package breaks gcc and cc on linux system.

See: https://stackoverflow.com/questions/38879672/g-as-fails-to-determine-which-assembler-to-run

**Comment by tpoechtrager** [comment]
`cctools-port` shouldn't be installed to `/usr` without providing a `--target=` prefix.

`./configure --target=x86_64-apple-darwin19`

Reinstall `binutils` on your system.
