### ISSUE TITLE
Running install_name_tool on a binary that has been executed is un-signable.

### ISSUE THREAD

**Issue by erykoff** [tpoechtrager/cctools-port#97]
There is a bug (feature?) in macos 11.1 (at least) on Apple Silicon that can have `install_name_tool` make an unsignable binary.   Note that this is a problem with both the system `install_name_tool` and the cctools-port version.  Fortunately, there is a workaround that can be used with cctools-port.  This bug is related to https://openradar.appspot.com/FB8914243 but is a slightly different manifestation.  Special thanks to @xhochy for figuring a bunch of this out!

If we take a simple `hello_world.c` program:
```
#include <stdio.h>

int main() {
  printf("Hello, world!\n");
}
```
The following sequence of commands will succeed (using either `codesign` or `ldid` and using system or cctools-port `install_name_tool`):
```
rm hello_world
clang -o hello_world hello_world.c
install_name_tool -add_rpath ./ hello_world
codesign -s - -f hello_world
./hello_world
```

The following sequence of commands will fail (replacing as above) if we execute `hello_world` before running `install_name_tool`:
```
rm hello_world
clang -o hello_world hello_world.c
./hello_world
install_name_tool -add_rpath ./ hello_world
codesign -s - -f hello_world
```
The error reported is `hello_world: the codesign_allocate helper tool cannot be found or used` but actually what happened is that `hello_world` is in a corrupted and unsignable state and you can find in the kernel log that the binary has been `tainted` (`(signed:1 validated:1 tainted:1 nx:0 wpmapped:0 dirty:0 depth:0)`) and won't run.  Sometimes, for reasons I don't understand, this can also happen with `.so` files, but not in any replicatable pattern that I can report.

Notably, this can be fixed by copying the file before running `install_name_tool` (which is why I think it's related to the radar linked above):
```
rm hello_world hello_world2
clang -o hello_world hello_world.c
./hello_world
cp hello_world hello_world2
install_name_tool -add_rpath ./ hello_world2
codesign -s - -f hello_world2
rm hello_world
mv hello_world2 hello_world
./hello_world
```
Luckily, we can't patch the system `install_name_tool` but we can patch this ported version to make a copy to a temporary file prior to running, when executed on Apple Silicon.

**Comment by tpoechtrager** [comment]
Merged your PR. Thanks!
